apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: service-callee
  name: service-callee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-callee
  template:
    metadata:
      labels:
        app: service-callee
    spec:
      containers:
      - image: myagmarbat/mg_repo:service-callee
        name: service-callee
        env:
        - name: RANDOM_HASH
          value: random
        - name: WAIT_BEFORE_SERVER_CLOSE
          value: "10"
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 2
          periodSeconds: 1
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: service-callee
  name: service-callee
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: service-callee
  type: ClusterIP
